import React from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import UserProvider from "@/components/UserProvider";
import { createClient } from "@/lib/supabase/server";
import Topbar from "@/components/Topbar";
import { Toaster } from "sonner";
import BottomNav from "@/components/BottomNav";
import ProposeEventModal from "@/components/ProposeEventModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CampusEvents",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  const { data: profile } = user
    ? await supabase
        .from("profiles")
        .select("display_name")
        .eq("id", user.id)
        .single()
    : { data: null };

  const displayName =
    profile?.display_name ?? user?.user_metadata?.full_name ?? "";

  return (
    <html lang="pl" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`bg-background ${geistSans.variable} ${geistMono.variable}`}
      >
        <UserProvider user={user} displayName={displayName}>
          <Sidebar />
          <BottomNav />
          <ProposeEventModal />
          <div className="md:ml-15 lg:ml-50 h-svh flex flex-col overflow-hidden">
            <Topbar />
            <main className="flex-1 flex flex-col min-h-0 overflow-y-auto pb-19 md:pb-0">
              {children}
            </main>
            <Toaster
              position="top-center"
              toastOptions={{
                classNames: { icon: "text-accent" },
              }}
            />
          </div>
        </UserProvider>
      </body>
    </html>
  );
}
