import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import UserProvider from "@/components/UserProvider";
import { createClient } from "@/lib/supabase/server";
import Topbar from "@/components/Topbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CampusEvents",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  return (
    <html lang="pl" suppressHydrationWarning>
      <body
        className={`bg-background ${geistSans.variable} ${geistMono.variable}`}
      >
        <UserProvider user={user}>
          <Sidebar />
          <div className="md:ml-15 lg:ml-50 h-svh flex flex-col overflow-hidden">
            <Topbar />
            <main className="flex-1 flex flex-col min-h-0">{children}</main>
          </div>
        </UserProvider>
      </body>
    </html>
  );
}
